name: "Баг | Bug Report"
description: "Сообщить об ошибке в CofeMine Launcher | File a bug report for CofeMine Launcher."
title: "[Bug] "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        RU: Перед отправкой проверь, что это ошибка лаунчера, а не краш Minecraft. Если Minecraft падает — сначала проверь логи игры и модов.
        RU: Если нужна помощь, пиши в Telegram или Discord:
        - Telegram: https://t.me/+rfvGU6sDSvEwZDgy
        - Discord: https://discord.gg/zyKM2XAnXW

        EN: Before submitting, confirm it is a launcher bug, not a Minecraft crash. If Minecraft crashes, check game/mod logs first.
        EN: Need help? Join:
        - Telegram: https://t.me/+rfvGU6sDSvEwZDgy
        - Discord: https://discord.gg/zyKM2XAnXW
  - type: textarea
    id: summary
    attributes:
      label: "Кратко | Summary"
      description: "RU: Коротко опиши проблему. EN: краткое описание."
      placeholder: "RU: Кнопка «Запуск» не реагирует... / EN: The Launch button does nothing..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Шаги воспроизведения | Steps to reproduce"
      description: "RU: Пошагово. EN: step-by-step."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Ожидаемое поведение | Expected behavior"
      description: "RU: Что должно было произойти. EN: expected result."
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: "Фактическое поведение | Actual behavior"
      description: "RU: Что произошло на самом деле. EN: actual result."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Логи / краш-репорт | Logs / crash report"
      description: |
        RU: Приложи лог лаунчера или crash-report. Это ключевая информация для диагностики.
        EN: Attach launcher logs or a crash report. This is critical for diagnosis.
    validations:
      required: true
