name: "Ошибка | Bug Report"
description: "RU: Сообщить об ошибке в CofeMine Launcher. EN: File a bug report for CofeMine Launcher."
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        RU: Перед отправкой убедитесь, что это ошибка лаунчера, а не краш Minecraft. Если падает игра — сначала проверьте логи игры/модов.
        RU: Нужна помощь? Напишите нам:
        - Telegram: https://t.me/+rfvGU6sDSvEwZDgy
        - Discord: https://discord.gg/zyKM2XAnXW

        EN: Please confirm this is a launcher bug, not a Minecraft crash. If the game crashes, check game/mod logs first.
        EN: Need help? Join:
        - Telegram: https://t.me/+rfvGU6sDSvEwZDgy
        - Discord: https://discord.gg/zyKM2XAnXW
  - type: textarea
    id: summary
    attributes:
      label: "Кратко | Summary"
      description: "RU: Что сломалось и где. EN: What is broken and where."
      placeholder: "RU: Кнопка Играть не реагирует... / EN: Play button does nothing..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Шаги | Steps to reproduce"
      description: "RU: Пошагово опишите, как повторить. EN: Step-by-step."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Ожидаемое поведение | Expected behavior"
      description: "RU: Что должно было произойти. EN: Expected result."
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: "Фактическое поведение | Actual behavior"
      description: "RU: Что произошло на самом деле. EN: Actual result."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Логи / Crash report"
      description: |
        RU: Приложите логи лаунчера или crash-report. Это сильно ускорит диагностику.
        EN: Attach launcher logs or a crash report. This is critical for diagnosis.
    validations:
      required: true
