name: "Идея | Feature Request"
description: "Предложить улучшение для CofeMine Launcher | Suggest a feature for CofeMine Launcher."
title: "[Feature] "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        RU: Пожалуйста, проверь, не создана ли уже похожая заявка.
        EN: Please check for existing similar requests before submitting.
  - type: textarea
    id: summary
    attributes:
      label: "Суть предложения | Summary"
      description: "RU: Что именно хочешь добавить. EN: what you want to add."
      placeholder: "RU: Добавить... / EN: Add..."
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: "Зачем это нужно | Why"
      description: "RU: Почему это важно. EN: why this matters."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "Детали | Details"
      description: "RU: Примеры, UX, варианты реализации. EN: examples, UX notes, implementation ideas."
    validations:
      required: false
